# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxgpdlZ62F3JfDEaAxtlKiVcIYLvRX2q
"""

from google.colab import drive
drive.mount('/content/drive')

!pip -q install ultralytics roboflow

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="NePZi3SOHsEPthDnGgCR")
project = rf.workspace("chirag-urfsw").project("chessboard-detection-yqcnu-mwmwu")
version = project.version(1)
dataset = version.download("yolov11")

import glob, yaml
from pathlib import Path

yamls = glob.glob("/content/chessboard-detection-1/data.yaml", recursive=True)
if not yamls:
    raise FileNotFoundError("data.yaml not found in the unzipped folder.")
DATA_YAML = yamls[0]
yaml_path = Path(DATA_YAML)
root = yaml_path.parent

with open(DATA_YAML, "r") as f:
    data = yaml.safe_load(f)

# Make train/val/test absolute so Ultralytics always finds images/labels
for k in ["train", "val", "test"]:
    if k in data and data[k]:
        p = Path(str(data[k]))
        if not p.is_absolute():
            data[k] = str((root / p).resolve())

with open(DATA_YAML, "w") as f:
    yaml.safe_dump(data, f, sort_keys=False)

print("Using data.yaml:", DATA_YAML)
!cat "{DATA_YAML}"

from ultralytics import YOLO

MODEL  = "yolo11s.pt"   # try yolo11s.pt if you want better accuracy
EPOCHS = 100
IMGSZ  = 512

model = YOLO(MODEL)
model.train(
    data=DATA_YAML,
    epochs=EPOCHS,
    imgsz=IMGSZ,
    batch=-1,     # auto
    device=0
)

!zip -r /content/Training_YOLO_Corner.zip /content/runs/detect/train

