# -*- coding: utf-8 -*-
"""YOLO_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LWZj-UYC4arBFWQ-TezZ8YuD0LNWCrP
"""

!pip install roboflow

# !pip install -U ultralytics pyyaml
from pathlib import Path
import zipfile, yaml

ZIP_PATH = Path("/content/Chess Pieces.v24-416x416_aug.yolov11.zip")  # your zip
ROOT = Path("/content/roboflow_chess_full")                           # where to extract
ROOT.mkdir(parents=True, exist_ok=True)

# --- extract ---
with zipfile.ZipFile(ZIP_PATH, "r") as zf:
    zf.extractall(ROOT)

print("Extracted to:", ROOT)

# --- find data.yaml (Roboflow export places it near the split folders) ---
data_yaml = next(ROOT.rglob("data.yaml"), None)
assert data_yaml is not None, "data.yaml not found inside the ZIP contents."

# --- rewrite train/val/test to absolute paths (prevents path issues) ---
with open(data_yaml, "r") as f:
    cfg = yaml.safe_load(f)

base = data_yaml.parent
def _abs(p):
    return str((base / p).resolve())

for k in ("train", "val", "test"):
    if k in cfg and cfg[k]:
        cfg[k] = _abs(cfg[k])

# ensure 'nc' aligns with 'names'
if "names" in cfg and "nc" not in cfg:
    cfg["nc"] = len(cfg["names"]) if isinstance(cfg["names"], list) else len(cfg["names"].keys())

with open(data_yaml, "w") as f:
    yaml.safe_dump(cfg, f, sort_keys=False)

print("Using data.yaml:", data_yaml)
print("train:", cfg.get("train"))
print("val:", cfg.get("val"))
print("test:", cfg.get("test"))

!pip install ultralytics

from ultralytics import YOLO
import torch, platform
print("Torch:", torch.__version__, "| CUDA:", torch.cuda.is_available())

# choose a size for your GPU: n/s/m/l/x  (start with n or s)
model = YOLO("yolo11s.pt")

results = model.train(
    data=str(data_yaml),
    epochs=100,
    imgsz=512,         # lower to 512/448 if VRAM is tight
    batch=16,          # drop to 8/4 if you see CUDA OOM
    device=0,
    pretrained=True,
)

metrics = model.val(data=str(data_yaml), imgsz=640, device=0)
print(metrics)

# best weights path
from pathlib import Path
best = sorted(Path("runs/detect").rglob("weights/best.pt"))[-1]
print("Best weights:", best)

# run predictions on the val set (or any folder/file)
model = YOLO(str(best))
model.predict(source="/content/roboflow_chess_full/valid/images", imgsz=640, conf=0.25, device=0)

from google.colab import files
import shutil

# Replace this with your folder path:
folder_path = "/content/runs/detect/val4"
# folder_path = "/content/runs/detect/train2"

# Create a zip file
shutil.make_archive("download_me", "zip", folder_path)

# Download it
files.download("download_me.zip")